
export interface PatternDef {
  id: string;
  name: string;
  shortDesc: string;
  fullDesc: string;
  formation: string;
  signals: string;
  context: string;
  risks: string;
  trend: string;
  example: string;
  identification: string; // New field for identification tip
  category: 'Reversal' | 'Continuation' | 'Bilateral' | 'Neutral';
}

export const PATTERNS_DB: PatternDef[] = [
  {
    id: "head-shoulders",
    name: "Ombro Cabeça Ombro (OCO)",
    shortDesc: "Padrão clássico de reversão de alta para baixa.",
    fullDesc: "O OCO é um dos padrões de reversão mais confiáveis. É formado por três topos: o primeiro (ombro esquerdo), o segundo mais alto (cabeça) e o terceiro mais baixo (ombro direito), conectados por uma linha de pescoço.",
    formation: "Três picos consecutivos, sendo o central o mais alto. A linha de pescoço conecta os fundos.",
    signals: "Rompimento da linha de pescoço com volume elevado.",
    context: "Final de tendência de alta prolongada.",
    risks: "Se a linha de pescoço não for rompida, o padrão é invalidado.",
    trend: "Reversão de Alta para Baixa (Bearish).",
    example: "Topo de mercado em 2021 no Bitcoin.",
    identification: "Busque 3 topos: o do meio deve ser o mais alto. Trace uma linha conectando os fundos (pescoço). A venda ocorre no rompimento dessa linha.",
    category: "Reversal"
  },
  {
    id: "inverse-head-shoulders",
    name: "OCO Invertido",
    shortDesc: "Padrão de reversão de baixa para alta.",
    fullDesc: "Espelho do OCO, formado por três fundos. O central é o mais profundo (cabeça), ladeado por dois fundos menos profundos (ombros).",
    formation: "Três vales, sendo o central o mais baixo.",
    signals: "Rompimento da linha de pescoço para cima.",
    context: "Final de tendência de baixa (fundo de mercado).",
    risks: "Falso rompimento da resistência.",
    trend: "Reversão de Baixa para Alta (Bullish).",
    example: "Fundo do mercado cripto em 2018.",
    identification: "Identifique 3 fundos, com o central sendo o mais baixo. A compra é acionada quando o preço rompe a resistência (linha de pescoço) para cima.",
    category: "Reversal"
  },
  {
    id: "double-top",
    name: "Topo Duplo (M)",
    shortDesc: "Reversão baixista com dois picos no mesmo nível.",
    fullDesc: "Formação em 'M' onde o preço falha em renovar a máxima duas vezes consecutivas, encontrando resistência na mesma zona.",
    formation: "Dois topos nivelados separados por um vale.",
    signals: "Perda do suporte (fundo entre os topos).",
    context: "Após forte tendência de alta exausta.",
    risks: "Transformação em canal lateral ou triângulo.",
    trend: "Bearish (Baixa).",
    example: "Resistência histórica em $69k.",
    identification: "Procure formato de 'M' no topo. Os dois picos devem estar quase na mesma altura. O gatilho de venda é a perda do fundo entre eles.",
    category: "Reversal"
  },
  {
    id: "double-bottom",
    name: "Fundo Duplo (W)",
    shortDesc: "Reversão altista com dois fundos no mesmo nível.",
    fullDesc: "Formação em 'W' indicando forte suporte. O preço testa a mínima duas vezes e rejeita a queda.",
    formation: "Dois vales nivelados separados por um pico.",
    signals: "Rompimento da resistência (topo entre os fundos).",
    context: "Fim de tendência de baixa.",
    risks: "Continuação da queda se o suporte romper.",
    trend: "Bullish (Alta).",
    example: "Recuperação em V ou W clássica.",
    identification: "Busque um 'W' no fundo do gráfico. Os dois fundos devem respeitar a mesma zona de suporte. Compre no rompimento do topo central.",
    category: "Reversal"
  },
  {
    id: "triple-top",
    name: "Topo Triplo",
    shortDesc: "Reversão forte com três toques na resistência.",
    fullDesc: "Variação mais forte do Topo Duplo. O preço testa a resistência três vezes antes de perder o suporte.",
    formation: "Três picos na mesma altura.",
    signals: "Quebra do suporte inferior.",
    context: "Exaustão extrema de compradores.",
    risks: "Formação de retângulo lateral.",
    trend: "Bearish (Baixa).",
    example: "Distribuição institucional prolongada.",
    identification: "Três tentativas falhas de romper o mesmo preço. Aguarde a perda do suporte inferior para confirmar a reversão.",
    category: "Reversal"
  },
  {
    id: "triple-bottom",
    name: "Fundo Triplo",
    shortDesc: "Acumulação sólida com três toques no suporte.",
    fullDesc: "Padrão raro e poderoso de reversão altista, onde o suporte é defendido três vezes consecutivas.",
    formation: "Três vales na mesma zona de preço.",
    signals: "Rompimento da resistência superior.",
    context: "Acumulação em fundo de mercado.",
    risks: "Demora na confirmação.",
    trend: "Bullish (Alta).",
    example: "Bases sólidas de longo prazo.",
    identification: "O preço bate 3 vezes no suporte e não cai. A confirmação de compra ocorre apenas quando rompe a resistência acima.",
    category: "Reversal"
  },
  {
    id: "rising-wedge",
    name: "Cunha de Alta (Bearish)",
    shortDesc: "Padrão de baixa formado por topos e fundos convergentes subindo.",
    fullDesc: "Apesar do nome 'Alta', é um padrão baixista. O preço sobe, mas com perda de momentum, comprimindo-se em um ápice.",
    formation: "Linhas de tendência de alta convergindo.",
    signals: "Rompimento da linha de suporte inferior.",
    context: "Correção em tendência de baixa ou exaustão de alta.",
    risks: "Confusão com canal de alta.",
    trend: "Bearish (Baixa).",
    example: "Perda de força em pullbacks.",
    identification: "Trace duas linhas subindo que se estreitam. O preço sobe 'cansado'. Quando perder a linha de baixo, a queda acelera.",
    category: "Reversal"
  },
  {
    id: "falling-wedge",
    name: "Cunha de Baixa (Bullish)",
    shortDesc: "Padrão de alta formado por topos e fundos convergentes caindo.",
    fullDesc: "Padrão altista. O preço cai, mas a pressão vendedora diminui, preparando um estouro para cima.",
    formation: "Linhas de tendência de baixa convergindo.",
    signals: "Rompimento da linha de resistência superior.",
    context: "Correção em tendência de alta ou fim de baixa.",
    risks: "Rompimento falso para baixo (raro).",
    trend: "Bullish (Alta).",
    example: "Acumulação final antes do pump.",
    identification: "Trace duas linhas caindo que se encontram lá na frente. A queda perde força. O rompimento da linha superior ativa a compra.",
    category: "Reversal"
  },
  {
    id: "bull-flag",
    name: "Bandeira de Alta",
    shortDesc: "Padrão de continuação após mastro forte.",
    fullDesc: "Consolidação curta e inclinada contra a tendência após um movimento explosivo (mastro).",
    formation: "Canal paralelo descendente após alta vertical.",
    signals: "Rompimento da resistência do canal.",
    context: "Meio de uma tendência de alta forte.",
    risks: "Se a bandeira for muito longa, perde força.",
    trend: "Continuação de Alta.",
    example: "Pumps escalonados.",
    identification: "Identifique um 'mastro' (alta forte) seguido de uma correção suave e curta. O rompimento do topo da correção retoma a alta.",
    category: "Continuation"
  },
  {
    id: "bear-flag",
    name: "Bandeira de Baixa",
    shortDesc: "Continuação de queda após mastro negativo.",
    fullDesc: "Consolidação curta e inclinada para cima após uma queda brusca.",
    formation: "Canal paralelo ascendente após queda vertical.",
    signals: "Perda do suporte do canal.",
    context: "Meio de uma tendência de baixa forte.",
    risks: "Reversão se o canal romper para cima.",
    trend: "Continuação de Baixa.",
    example: "Cascata de liquidação.",
    identification: "Queda forte (mastro) seguida de uma subida fraca e lenta. Quando perder o fundo dessa subida, a queda continua.",
    category: "Continuation"
  },
  {
    id: "bull-pennant",
    name: "Flâmula de Alta",
    shortDesc: "Pequeno triângulo simétrico após alta.",
    fullDesc: "Similar à bandeira, mas as linhas convergem como um triângulo pequeno.",
    formation: "Mastro seguido de compressão triangular.",
    signals: "Rompimento do topo da flâmula.",
    context: "Momentum muito forte.",
    risks: "Volume decrescente é essencial na formação.",
    trend: "Continuação de Alta.",
    example: "Pausa breve em ralis parabólicos.",
    identification: "Alta explosiva seguida de um pequeno triângulo lateral. É uma pausa para respirar antes de subir mais.",
    category: "Continuation"
  },
  {
    id: "bear-pennant",
    name: "Flâmula de Baixa",
    shortDesc: "Pequeno triângulo simétrico após queda.",
    fullDesc: "Compressão triangular após um despejo forte de preços.",
    formation: "Mastro de baixa seguido de compressão.",
    signals: "Perda do fundo da flâmula.",
    context: "Panic selling com pausa breve.",
    risks: "Falso rompimento.",
    trend: "Continuação de Baixa.",
    example: "Pausa antes de nova mínima.",
    identification: "Queda vertical seguida de um pequeno triângulo. Indica que vendedores estão recarregando para derrubar mais o preço.",
    category: "Continuation"
  },
  {
    id: "asc-triangle",
    name: "Triângulo Ascendente",
    shortDesc: "Topo plano e fundos ascendentes. Bullish.",
    fullDesc: "Pressão de compra constante empurrando o preço contra uma resistência fixa.",
    formation: "Resistência horizontal e LTA (Linha de Tendência de Alta).",
    signals: "Rompimento da resistência horizontal.",
    context: "Geralmente continuação de alta.",
    risks: "Topo duplo se falhar em romper.",
    trend: "Bullish (Alta).",
    example: "Acumulação sob resistência chave.",
    identification: "Topo reto (resistência) e fundos cada vez mais altos. Compradores estão pressionando o teto até estourar.",
    category: "Continuation"
  },
  {
    id: "desc-triangle",
    name: "Triângulo Descendente",
    shortDesc: "Fundo plano e topos descendentes. Bearish.",
    fullDesc: "Pressão de venda constante empurrando o preço contra um suporte fixo.",
    formation: "Suporte horizontal e LTB (Linha de Tendência de Baixa).",
    signals: "Perda do suporte horizontal.",
    context: "Geralmente continuação de baixa.",
    risks: "Fundo duplo se o suporte segurar.",
    trend: "Bearish (Baixa).",
    example: "Distribuição antes do crash.",
    identification: "Fundo reto (suporte) e topos cada vez mais baixos. Vendedores estão empurrando o preço contra o chão até quebrar.",
    category: "Continuation"
  },
  {
    id: "sym-triangle",
    name: "Triângulo Simétrico",
    shortDesc: "Compressão bilateral. Aguardar rompimento.",
    fullDesc: "O mercado está indeciso, com topos mais baixos e fundos mais altos convergindo.",
    formation: "LTA e LTB convergindo simetricamente.",
    signals: "Rompimento para qualquer lado com volume.",
    context: "Consolidação antes de grande movimento.",
    risks: "Muitos falsos rompimentos (Fakeouts).",
    trend: "Bilateral (Segue o rompimento).",
    example: "Contração de volatilidade.",
    identification: "Topos caindo e fundos subindo. O preço está sendo espremido. Opere a favor do lado que romper com volume.",
    category: "Bilateral"
  },
  {
    id: "cup-handle",
    name: "Cup and Handle",
    shortDesc: "Xícara e Alça. Padrão de alta de longo prazo.",
    fullDesc: "Fundo arredondado seguido de um pullback leve (alça) antes de romper a resistência.",
    formation: "Forma de 'U' seguida de bandeira de baixa curta.",
    signals: "Rompimento da resistência da xícara.",
    context: "Reversão ou continuação de alta em tempos gráficos maiores.",
    risks: "Alça muito profunda invalida o padrão.",
    trend: "Bullish (Alta).",
    example: "Reacumulação institucional.",
    identification: "Parece uma xícara de chá. O 'U' é a xícara, a pequena queda à direita é a alça. Compre quando o preço superar a borda da xícara.",
    category: "Continuation"
  },
  {
    id: "inv-cup-handle",
    name: "Cup & Handle Invertido",
    shortDesc: "Padrão de baixa de longo prazo.",
    fullDesc: "Topo arredondado seguido de um repique leve antes de perder o suporte.",
    formation: "Forma de 'U' invertido seguida de bandeira de alta curta.",
    signals: "Perda do suporte da borda.",
    context: "Distribuição lenta.",
    risks: "Recuperação em V anula o padrão.",
    trend: "Bearish (Baixa).",
    example: "Topo arredondado de mercado.",
    identification: "Uma xícara de cabeça para baixo. Quando o preço perder o suporte da 'alça' (pequena alta corretiva), a tendência é de queda forte.",
    category: "Continuation"
  },
  {
    id: "diamond-top",
    name: "Diamante de Reversão",
    shortDesc: "Volatilidade expandindo e contraindo no topo.",
    fullDesc: "Padrão raro de reversão de topo, parecendo um losango. Indica confusão e exaustão.",
    formation: "Broadening pattern seguido de triângulo simétrico.",
    signals: "Perda do suporte do diamante.",
    context: "Topos de mercado muito voláteis.",
    risks: "Difícil identificação.",
    trend: "Bearish (Baixa).",
    example: "Topo do Bitcoin em certos ciclos.",
    identification: "O preço abre como um megafone e depois fecha como um triângulo. Parece um balão ou diamante. A perda do fundo confirma a queda.",
    category: "Reversal"
  },
  {
    id: "rectangle-bull",
    name: "Retângulo de Alta",
    shortDesc: "Caixa de acumulação em tendência de alta.",
    fullDesc: "O preço anda de lado entre suporte e resistência paralelos após uma alta.",
    formation: "Canal lateral horizontal.",
    signals: "Rompimento da resistência.",
    context: "Pausa para reacumulação.",
    risks: "Pode virar reversão se perder o fundo.",
    trend: "Continuação de Alta.",
    example: "Range de acumulação.",
    identification: "O preço fica preso numa caixa lateral após subir. Se romper o teto da caixa, a tendência de alta continua.",
    category: "Continuation"
  },
  {
    id: "rectangle-bear",
    name: "Retângulo de Baixa",
    shortDesc: "Caixa de distribuição em tendência de baixa.",
    fullDesc: "O preço anda de lado entre suporte e resistência paralelos após uma queda.",
    formation: "Canal lateral horizontal.",
    signals: "Perda do suporte.",
    context: "Pausa para redistribuição.",
    risks: "Pode virar fundo duplo se romper topo.",
    trend: "Continuação de Baixa.",
    example: "Range de distribuição.",
    identification: "O preço fica preso numa caixa lateral após cair. Se perder o fundo da caixa, a tendência de baixa continua.",
    category: "Continuation"
  },
  {
    id: "broadening-top",
    name: "Broadening Top",
    shortDesc: "Megafone de topo. Alta volatilidade.",
    fullDesc: "Topos mais altos e fundos mais baixos divergindo. Sinal de descontrole emocional do mercado.",
    formation: "Linhas divergentes (Megafone).",
    signals: "Geralmente rompe para baixo em topos.",
    context: "Final de bolha ou euforia.",
    risks: "Stop loss difícil devido à volatilidade.",
    trend: "Bearish (Reversão).",
    example: "Mercado instável.",
    identification: "O mercado fica 'louco', fazendo topos maiores e fundos menores (formato de megafone). Geralmente acaba rompendo para baixo.",
    category: "Reversal"
  },
  {
    id: "broadening-bottom",
    name: "Broadening Bottom",
    shortDesc: "Megafone de fundo.",
    fullDesc: "Padrão de alargamento no fundo do mercado, indicando capitulação e briga intensa.",
    formation: "Linhas divergentes em fundo.",
    signals: "Rompimento da resistência superior.",
    context: "Fundo de pânico.",
    risks: "Alta volatilidade.",
    trend: "Bullish (Reversão).",
    example: "Capitulação final.",
    identification: "Megafone no fundo do gráfico. Indica pânico final. Se o preço conseguir romper o topo da estrutura, pode reverter para alta.",
    category: "Reversal"
  },
  {
    id: "bump-run",
    name: "Bump and Run",
    shortDesc: "Aceleração especulativa e crash.",
    fullDesc: "O preço sobe suavemente (Lead-in), acelera parabolicamente (Bump) e reverte rápido (Run).",
    formation: "Parábola insustentável.",
    signals: "Perda da linha de tendência acelerada.",
    context: "Estouro de bolhas.",
    risks: "Vender cedo demais durante o Bump.",
    trend: "Reversão Bearish.",
    example: "Pump and Dump clássico.",
    identification: "Uma alta que de repente fica vertical (Bump). Quando essa linha vertical é perdida, o preço 'corre' para baixo (Run).",
    category: "Reversal"
  },
  {
    id: "adam-eve-double-bottom",
    name: "Adam & Eve Bottom",
    shortDesc: "Fundo duplo com formatos diferentes.",
    fullDesc: "Primeiro fundo é agudo (Adam - V), segundo fundo é arredondado (Eve - U).",
    formation: "Espigão em V seguido de curva em U.",
    signals: "Rompimento da resistência.",
    context: "Reversão de baixa sólida.",
    risks: "Eve falhar em completar o U.",
    trend: "Bullish (Alta).",
    example: "Recuperação sustentável.",
    identification: "Um fundo pontudo (V) seguido de um fundo suave (U). Mostra que a venda agressiva parou e a acumulação começou.",
    category: "Reversal"
  },
  {
    id: "adam-eve-double-top",
    name: "Adam & Eve Top",
    shortDesc: "Topo duplo com formatos diferentes.",
    fullDesc: "Primeiro topo agudo (V invertido), segundo topo arredondado (U invertido).",
    formation: "Pico agudo seguido de domo.",
    signals: "Perda do suporte.",
    context: "Reversão de alta.",
    risks: "Confusão com consolidação.",
    trend: "Bearish (Baixa).",
    example: "Exaustão de compra lenta.",
    identification: "Um topo pontudo (V invertido) seguido de um topo arredondado. Mostra exaustão da compra. Venda na perda do suporte.",
    category: "Reversal"
  },
  {
    id: "rounding-bottom",
    name: "Rounding Bottom",
    shortDesc: "Fundo arredondado (Saucer).",
    fullDesc: "Mudança gradual de sentimento de venda para compra, formando um prato.",
    formation: "Curva suave em U.",
    signals: "Preço supera a borda esquerda.",
    context: "Acumulação de longo prazo.",
    risks: "Processo muito lento.",
    trend: "Bullish (Reversão).",
    example: "Ciclos de mercado lentos.",
    identification: "O gráfico faz uma curva suave, parecendo um prato fundo. Indica transição lenta de mãos fracas para fortes.",
    category: "Reversal"
  },
  {
    id: "rounding-top",
    name: "Rounding Top",
    shortDesc: "Topo arredondado (Domo).",
    fullDesc: "Mudança gradual de sentimento de compra para venda.",
    formation: "Curva suave em U invertido.",
    signals: "Perda do suporte da base.",
    context: "Distribuição institucional lenta.",
    risks: "Pode ser apenas uma pausa.",
    trend: "Bearish (Reversão).",
    example: "Fim de ciclo suave.",
    identification: "O gráfico faz uma curva suave no topo (domo). Indica que os grandes players estão vendendo aos poucos sem derrubar o preço imediatamente.",
    category: "Reversal"
  },
  {
    id: "ascending-channel",
    name: "Canal de Alta",
    shortDesc: "Tendência de alta ordenada.",
    fullDesc: "Preço oscila entre duas linhas paralelas inclinadas para cima.",
    formation: "LTA e linha de retorno paralelas.",
    signals: "Operar as bordas ou rompimento.",
    context: "Tendência saudável.",
    risks: "Rompimento para baixo indica reversão.",
    trend: "Bullish (Sustentação).",
    example: "Bull market orgânico.",
    identification: "O preço sobe respeitando dois trilhos paralelos. Compre no trilho de baixo e realize lucro no de cima.",
    category: "Continuation"
  },
  {
    id: "descending-channel",
    name: "Canal de Baixa",
    shortDesc: "Tendência de baixa ordenada.",
    fullDesc: "Preço oscila entre duas linhas paralelas inclinadas para baixo.",
    formation: "LTB e linha de retorno paralelas.",
    signals: "Rompimento para cima indica reversão.",
    context: "Correção saudável ou Bear Market.",
    risks: "Aceleração da queda se romper fundo.",
    trend: "Bearish (Sustentação).",
    example: "Correção ABC.",
    identification: "O preço desce respeitando dois trilhos paralelos. Venda no trilho de cima e recompre no de baixo.",
    category: "Continuation"
  },
  {
    id: "rising-wedge-rev",
    name: "Cunha de Reversão (Baixa)",
    shortDesc: "Cunha de alta aparecendo no topo.",
    fullDesc: "Idêntica à Cunha de Alta, mas ocorre no final de uma tendência de alta, sinalizando topo.",
    formation: "Convergência ascendente.",
    signals: "Perda da LTA inferior.",
    context: "Exaustão de compradores.",
    risks: "Rompimento para cima (Blow-off top).",
    trend: "Reversão Bearish.",
    example: "Topo final.",
    identification: "Preço sobe se espremendo. Quando ocorre no topo, indica que a compra acabou. Perda da linha inferior causa crash.",
    category: "Reversal"
  },
  {
    id: "falling-wedge-rev",
    name: "Cunha de Reversão (Alta)",
    shortDesc: "Cunha de baixa aparecendo no fundo.",
    fullDesc: "Idêntica à Cunha de Baixa, mas ocorre no final de uma tendência de baixa.",
    formation: "Convergência descendente.",
    signals: "Rompimento da LTB superior.",
    context: "Exaustão de vendedores.",
    risks: "Continuação da queda.",
    trend: "Reversão Bullish.",
    example: "Fundo final.",
    identification: "Preço cai se espremendo. No fundo, indica que vendedores cansaram. Rompimento da linha superior reverte para alta.",
    category: "Reversal"
  },
  {
    id: "scallop-asc",
    name: "J Pattern (Scallop)",
    shortDesc: "Formato de gancho ou J.",
    fullDesc: "Uma queda rápida seguida de recuperação que não para, formando um J.",
    formation: "Fundo arredondado com lado direito vertical.",
    signals: "Continuação da alta vertical.",
    context: "Momentum especulativo.",
    risks: "Correção brusca.",
    trend: "Bullish (Aceleração).",
    example: "Altcoins em temporada.",
    identification: "O preço faz uma barriga e depois sobe reto, parecendo a letra 'J'. Comum em moedas muito voláteis.",
    category: "Continuation"
  },
  {
    id: "dead-cat-bounce",
    name: "Pulo do Gato Morto",
    shortDesc: "Recuperação falsa em crash.",
    fullDesc: "Uma queda massiva, um repique medíocre e continuação da queda.",
    formation: "Queda vertical, repique fraco, nova queda.",
    signals: "Perda da mínima do repique.",
    context: "Bear market agressivo.",
    risks: "Confundir com fundo real.",
    trend: "Bearish (Continuação).",
    example: "Crash de 2008 ou Crypto Winter.",
    identification: "Queda gigante, pequeno repique que não passa de 50% da queda, e depois perde o fundo novamente.",
    category: "Continuation"
  },
  {
    id: "island-reversal-top",
    name: "Island Reversal Top",
    shortDesc: "Topo isolado por gaps.",
    fullDesc: "Um gap de alta, consolidação no topo, e gap de baixa, deixando o topo isolado.",
    formation: "Gaps em ambos os lados da consolidação.",
    signals: "O gap de baixa confirma.",
    context: "Topo exaustivo.",
    risks: "Fechamento do gap invalida.",
    trend: "Reversão Bearish.",
    example: "Gap de exaustão.",
    identification: "Um bloco de candles fica isolado no topo, separado por buracos (gaps) na esquerda e direita. Sinal muito forte de topo.",
    category: "Reversal"
  },
  {
    id: "island-reversal-bottom",
    name: "Island Reversal Bottom",
    shortDesc: "Fundo isolado por gaps.",
    fullDesc: "Gap de baixa, consolidação, gap de alta, deixando o fundo isolado.",
    formation: "Ilha de preços isolada.",
    signals: "Gap de alta confirma.",
    context: "Fundo de pânico.",
    risks: "Preenchimento do gap.",
    trend: "Reversão Bullish.",
    example: "Reversão em V com gap.",
    identification: "Um bloco de candles fica isolado no fundo, separado por gaps. Indica que o mercado abandonou aquele nível de preço.",
    category: "Reversal"
  },
  {
    id: "expanding-triangle",
    name: "Expanding Triangle",
    shortDesc: "Triângulo invertido (Megafone Simétrico).",
    fullDesc: "Volatilidade crescente para ambos os lados. Mercado instável.",
    formation: "Linhas divergentes simétricas.",
    signals: "Difícil operar, aguardar rompimento claro.",
    context: "Incerteza máxima.",
    risks: "Violinadas constantes.",
    trend: "Bilateral (Indefinido).",
    example: "Notícias conflitantes.",
    identification: "O oposto do triângulo simétrico. O preço se abre. Muito perigoso, melhor esperar o mercado se acalmar.",
    category: "Bilateral"
  },
  {
    id: "harmonic-bat",
    name: "Padrão Morcego (Harmonic)",
    shortDesc: "Padrão harmônico de reversão.",
    fullDesc: "Estrutura XABCD específica com retrações de Fibonacci.",
    formation: "Perna XA, B em 0.38-0.5 XA, D em 0.886 XA.",
    signals: "Reversão no ponto D (PRZ).",
    context: "Mercado lateral ou reversão.",
    risks: "Invalidação das razões Fibo.",
    trend: "Reversão.",
    example: "Trading algorítmico.",
    identification: "Formato de 'M' ou 'W' específico onde as pernas respeitam níveis de Fibonacci (0.886). Requer ferramenta de medição.",
    category: "Reversal"
  },
  {
    id: "harmonic-gartley",
    name: "Padrão Gartley",
    shortDesc: "O clássico harmônico.",
    fullDesc: "Padrão M ou W específico com regras rígidas de Fibonacci.",
    formation: "B em 0.618 XA, D em 0.786 XA.",
    signals: "Entrada no ponto D.",
    context: "Pullback complexo.",
    risks: "Medição incorreta.",
    trend: "Reversão.",
    example: "Retrações profundas.",
    identification: "O pai dos harmônicos. Parece um 'M' ou 'W', mas o ponto B deve retrair exatamente 61.8% da perna inicial.",
    category: "Reversal"
  },
  {
    id: "three-black-crows",
    name: "Três Corvos Negros",
    shortDesc: "Reversão de candlestick forte.",
    fullDesc: "Três candles vermelhos longos consecutivos fechando perto das mínimas.",
    formation: "Três candles de baixa progressivos.",
    signals: "Confirmação de topo.",
    context: "Após alta prolongada.",
    risks: "Venda muito esticada (aguardar repique).",
    trend: "Reversão Bearish.",
    example: "Início de crash.",
    identification: "Três velas vermelhas grandes seguidas no topo, cada uma abrindo dentro da anterior e fechando mais baixo.",
    category: "Reversal"
  },
  {
    id: "three-white-soldiers",
    name: "Três Soldados Brancos",
    shortDesc: "Reversão de candlestick forte.",
    fullDesc: "Três candles verdes longos consecutivos fechando perto das máximas.",
    formation: "Três candles de alta progressivos.",
    signals: "Confirmação de fundo.",
    context: "Após baixa prolongada.",
    risks: "Compra esticada.",
    trend: "Reversão Bullish.",
    example: "Início de bull run.",
    identification: "Três velas verdes grandes seguidas no fundo, mostrando força compradora avassaladora.",
    category: "Reversal"
  },
  {
    id: "dragon-pattern",
    name: "Padrão Dragão",
    shortDesc: "Similar ao Fundo Duplo com cauda.",
    fullDesc: "Cabeça, duas patas (fundo duplo sendo o segundo mais baixo) e cauda (alvo).",
    formation: "W com perna C mais baixa que A.",
    signals: "Rompimento da linha de dorso (LTB).",
    context: "Fundo de mercado.",
    risks: "Falha na linha de tendência.",
    trend: "Reversão Bullish.",
    example: "Reversão exótica.",
    identification: "Parece um 'W' torto onde o segundo fundo é mais baixo. Trace uma linha da cabeça até a corcunda para achar o ponto de entrada.",
    category: "Reversal"
  },
  {
    id: "kicker-pattern",
    name: "Kicker Pattern",
    shortDesc: "Reversão mais forte de candles.",
    fullDesc: "Mudança súbita de direção com gap, anulando o candle anterior completamente.",
    formation: "Gap oposto ao candle anterior sem pavio.",
    signals: "Imediato.",
    context: "Notícia bomba.",
    risks: "Liquidez.",
    trend: "Explosiva.",
    example: "Evento Black Swan.",
    identification: "Uma vela verde seguida de um gap e uma vela vermelha gigante (ou vice-versa). Mostra mudança imediata de humor.",
    category: "Reversal"
  },
  {
    id: "consolidation-box",
    name: "Caixa de Consolidação",
    shortDesc: "Mercado sem direção.",
    fullDesc: "Preço preso em range estreito e longo.",
    formation: "Lateralidade compacta.",
    signals: "Explosão para qualquer lado.",
    context: "Aguardando catalisador.",
    risks: "Falsos rompimentos.",
    trend: "Neutro.",
    example: "Fim de semana ou feriado.",
    identification: "Velas pequenas lado a lado, sem subir nem descer. Aguarde sair da caixa para operar.",
    category: "Bilateral"
  },
  {
    id: "high-tight-flag",
    name: "Bandeira de Alta Justa",
    shortDesc: "Padrão mais forte de todos.",
    fullDesc: "Alta de 100%+ seguida de consolidação lateral mínima (10-20%).",
    formation: "Mastro gigante, bandeira minúscula.",
    signals: "Rompimento do topo.",
    context: "Superbolhas ou penny stocks.",
    risks: "Alta volatilidade.",
    trend: "Continuação Explosiva.",
    example: "Meme coins.",
    identification: "O preço dobra de valor rápido e depois anda de lado bem curtinho. Se romper, costuma dobrar de novo.",
    category: "Continuation"
  },
  {
    id: "hook-reversal",
    name: "Hook Reversal",
    shortDesc: "Inside bar em topos/fundos.",
    fullDesc: "Candle que falha em continuar a tendência e fecha dentro do anterior.",
    formation: "Harami com pavio de armadilha.",
    signals: "Perda da mínima/máxima.",
    context: "Exaustão de curto prazo.",
    risks: "Padrão fraco isoladamente.",
    trend: "Reversão Curta.",
    example: "Swing trade.",
    identification: "Uma vela que tenta romper a anterior mas falha e fecha dentro dela, parecendo um gancho.",
    category: "Reversal"
  },
  {
    id: "zig-zag",
    name: "Formação Zig Zag",
    shortDesc: "Correção complexa.",
    fullDesc: "Padrão de onda corretiva de Elliott (ABC) profundo.",
    formation: "5-3-5 ondas.",
    signals: "Fim da onda C.",
    context: "Correção de mercado.",
    risks: "Confundir com impulso.",
    trend: "Corretiva.",
    example: "Bear market rally.",
    identification: "Movimento em 3 pernas contra a tendência (A-B-C). Parece um raio.",
    category: "Continuation"
  },
  {
    id: "complex-h-s",
    name: "OCO Complexo",
    shortDesc: "Múltiplos ombros ou cabeças.",
    fullDesc: "Variação do OCO com dois ombros esquerdos ou duas cabeças.",
    formation: "Simetria complexa.",
    signals: "Linha de pescoço.",
    context: "Topos muito longos.",
    risks: "Difícil leitura.",
    trend: "Reversão Bearish.",
    example: "Topo de 2021 (Double Top OCO).",
    identification: "Um OCO 'mutante' com duas cabeças ou vários ombros. A lógica é a mesma: perdeu a base (pescoço), vendeu.",
    category: "Reversal"
  },
  {
    id: "parabolic-arc",
    name: "Arco Parabólico",
    shortDesc: "Aceleração exponencial.",
    fullDesc: "Preço sobe em curva cada vez mais vertical.",
    formation: "Curva exponencial.",
    signals: "Verticalização total (blow-off).",
    context: "FOMO extremo.",
    risks: "Queda livre a qualquer momento.",
    trend: "Exaustão.",
    example: "Bolhas.",
    identification: "O gráfico faz uma curva para cima cada vez mais inclinada. Quando fica vertical (90 graus), o colapso é iminente.",
    category: "Reversal"
  },
  {
    id: "v-top",
    name: "Topo em V",
    shortDesc: "Reversão súbita e violenta.",
    fullDesc: "O preço inverte direção sem consolidar no topo.",
    formation: "Pico único agudo.",
    signals: "Rejeição imediata.",
    context: "Notícia negativa em alta.",
    risks: "Impossível prever antes.",
    trend: "Reversão Bearish.",
    example: "Flash Crash.",
    identification: "Sobe rápido e cai rápido, sem avisar. Parece um 'V' invertido afiado.",
    category: "Reversal"
  },
  {
    id: "v-bottom",
    name: "Fundo em V",
    shortDesc: "Recuperação súbita e violenta.",
    fullDesc: "O preço inverte direção sem consolidar no fundo.",
    formation: "Vale único agudo.",
    signals: "Compra agressiva imediata.",
    context: "Notícia positiva em baixa.",
    risks: "Reteste do fundo.",
    trend: "Reversão Bullish.",
    example: "Intervenção de banco central.",
    identification: "Cai rápido e sobe rápido. Ocorre em notícias bombásticas.",
    category: "Reversal"
  }
];
